### ISSUE TITLE
Support fullscreen window

### ISSUE THREAD

**Issue by orontee** [orontee/argos#102]
I have a question about the maximized mode. If the title bar is pressed longer, the full screen mode is exited. The maximize, minimize and close buttons appear. Is it possible to disable this behavior in Gtk?

Thanks and greetings
André

_Originally posted by @canddoki in https://github.com/orontee/argos/issues/90#issuecomment-1315832799_

**Comment by orontee** [comment]
What you call "fullscreen" mode is currently implemented using a _maximized_ window. It was motivated by the following observation: When the window manager manages the title bar it usually hides the title bar for fullscreen windows.

But since Argos title bar is managed by the application itself, this should not be the case. Thus hopefully this annoying behavior should be fixed soon.

Maximized will be replaced by fullscreen.

**Comment by orontee** [comment]
Setting `start-maximized` is removed and a new `start-fullscreen` setting is introduced.

:warning: One must toggle the "start fullscreen" setting through the preferences dialog.

@canddoki With this feature branch, the main window is now unmovable while in fullscreen mode and the title bar is visible. Could you please confirm that it's ok on your side? I've made many tries to fix this and I may have residues of window manager settings affecting the issue at hand...

**Comment by canddoki** [comment]
@orontee I tested the branch with full screen mode. Double click, long press on the title bar and nothing happened - perfect 😀. Visually, it also looks very good, i.e. unchanged.

.../LXDE/run.log does not contain any significant errors.

Good work 👍
