### ISSUE TITLE
Can have volume control?

### ISSUE THREAD

**Issue by v-evets** [orontee/argos#145]
Ho, this app looks pretty tasty, exactly what I've been looking for to replace a nasty web browser on my repurposed ancient industrial touchscreen setup...
The only thing really missing is a touch-friendly volume /mixer control. Kinda scratching my head as to why it doesn't already have one already since that seems kinda obvious, but anyhow, wishlist item? Pretty Please?

**Comment by orontee** [comment]
> Ho, this app looks pretty tasty, exactly what I've been looking for to replace a nasty web browser on my repurposed ancient industrial touchscreen setup...

Cool!

> The only thing really missing is a touch-friendly volume /mixer control. Kinda scratching my head as to why it doesn't already have one already since that seems kinda obvious, but anyhow, wishlist item? Pretty Please?

It has one. Maybe not as friendly as you wish... It is on the bottom right, in what we call the "condensed playing box". See:

![Capture d’écran du 2023-07-11 14-56-26 (annotée)](https://github.com/orontee/argos/assets/2065954/f603b187-2be2-4d10-8e78-8f9fcfd3fed8)

If the button is hidden from your Argos instance, it means that there's no mixer enabled on Mopidy server side. To enable a mixer,  you can for example tweak Mopidy configuration to have the following lines, then restart Mopidy service and Argos UI should update automatically:
```
[audio]
mixer = software
...

[softwaremixer]
enabled = true
```

Let me know if it match your expectations.

**Comment by v-evets** [comment]
So it does, I completely missed it as I was looking on the "playing" tab, but it only appears in the miniplayer on the library tab.
Any chance of adding one to the "playing" screen as well? Maybe a bit bigger (i.e. longer slider) too?


Couple other probably-unique-to-my-weird-setup niggles:

* This contraption is connected directly to a ~350W RMS power amplifier. The volume slider is small, my fingers are fat, and there are only 5 steps between "off" and "deaf" using the "+" and "-" buttons on the volume widget... Any chance of (much) smaller or user-configurable volume steps? 

* A way to skip to a track on the playing/tracklist view other than double-clicking (which is a PITA on a resistive panel) would be very welcome. 
Maybe a "play" button or (dual-purposing the playing indicator) on each tracklist entry, or adding a "play track" button in the list header like the the other two views have?
A setting to use long-press instead of double-click globally would be ideal IMO, but I haven't looked into how feasible that would be or whether it's something I can hack around with at the xorg/evdev level.


Other than that, this is pretty sweet. Saves me ~400MB of RAM on the old POS (in both senses) machine I'm using to run it too :D

**Comment by kingosticks** [comment]
Are you able to use [Mopidy-AlsaMixer](https://github.com/mopidy/mopidy-alsamixer)? It has `min_volume` and `max_volume` config settings which allow you to remap the volume range for situations like this. Otherwise perhaps you can do something in Pulseuaudio (or whatever you are using), you can't solve this issue on the frontend.

**Comment by v-evets** [comment]
I'm already using mopidy-alsamixer, the issue isn't that the volume range is too wide (I actually need the full range), it's that the slider is too short for my fat fingers and low-accuracy resistive "prod" panel to make small adjustments.
The buttons don't help here, as they appear to be using the same step size as a scrollwheel click and that's huge - somewhere around 20% per.

The volume slider in mopidy-mobile is fine in this situation as it uses the full screen width, and so are clients with volume up and volume down buttons with a step size setting - an example being the MALP MPD client on android.
If I plug in a mouse I can (carefully) drag the slider in argo accurately enough too, with the hardware mixer responding as expected, so it's not a mixer problem.

**Comment by kingosticks** [comment]
Oh I see! Sorry, I misunderstood.

**Comment by orontee** [comment]
Let's
- [ ] Add an instance of the volume  button on the "Playing box"
- [ ] Change the step size of the volume slider
- [ ] Make sure that the volume slider and volume button have the right identifiers so that their size can be tweaked through CSS

**Comment by orontee** [comment]
> A way to skip to a track on the playing/tracklist view other than double-clicking (which is a PITA on a resistive panel) would be very welcome.

Why not use the "previous" and "next" button on the left side of the "playing box"?

> A setting to use long-press instead of double-click globally would be ideal IMO, but I haven't looked into how feasible that would be or whether it's something I can hack around with at the xorg/evdev level.

I'll have a look whether it's feasible with GTK3. No idea right now.

Would you mind opening a dedicated issue for this?

**Comment by orontee** [comment]
@v-evets Can you check branch https://github.com/orontee/argos/tree/145-can-have-volume-control?
The "playing box" has a volume button in its left pane and the page step of volume buttons has been divided by 10, so clicking on plus and minus buttons steps through 50 different volumes.

**Comment by v-evets** [comment]
Yep, that's most excellent. Works out very close to the volume step I'm using with MPD clients.
