### ISSUE TITLE
Entering album details page twice shows wrong album details

### ISSUE THREAD

**Issue by canddoki** [orontee/argos#26]
@orontee Yesterday I tried your new version with the extended preference dialog.
Since then I have observed the following:
After booting I can choose an album in the library and it opens in the album-view. But when I get back and choose an other album, in most cases the previous album appears again.
The second is a problem with the window size in vertical direction. I don't know if at every click, but from click to click pixels disappear at the bottom edge. May the uploaded image could help.
Cheers :)

**Comment by orontee** [comment]
Thanks! The window height problem isn't new to me and I confess it's really annoying. I created #27 to track work on this.

**Comment by orontee** [comment]
For the album details I understand that it is strange to see the previous album. Can you confirm that the album you want to see the details finally loads? 

We can unbind the model when exiting that "album details" page. As a result, when entering that page again, one won't see the old album but an empty page until album details are loaded.

Remember that argos doesn't serialize the model with albums, tracks, etc. it loads them from Mopidy server on demand.

**Comment by canddoki** [comment]
May the logfile could bring a bit light in it :).
[07-07-2022_lxde-run.log](https://github.com/orontee/argos/files/9066562/07-07-2022_lxde-run.log)

**Comment by orontee** [comment]
Commit e8778fb introduced a regression: It removes an unnecessary library lookup for already completed albums. As a side effect, the album details page isn't notified anymore of an album change when one enters an already completed album...

**Comment by orontee** [comment]
b7743e5 restore the library lookup on already completed albums. Browsing album details should be ok now. Sorry @canddoki !

**Comment by orontee** [comment]
https://github.com/orontee/argos/issues/27#issuecomment-1184752733
