### ISSUE TITLE
Window height isn't constant

### ISSUE THREAD

**Issue by orontee** [orontee/argos#27]
Visiting albums details sometimes increase the window size.
![177776390-b57d7dce-9776-465c-9c75-0315b8b06720](https://user-images.githubusercontent.com/2065954/177829296-5331cb7a-47b2-45c0-b4b4-2a62054028ba.jpeg)

**Comment by canddoki** [comment]
@orontee Don't worry, may others have the same problem 😊: https://stackoverflow.com/questions/7796101/how-to-correctly-restore-gtk-window-size-at-program-startup.
But in the version from last week the albumview is showing the correct album 👍.
Happy weekend...
