### ISSUE TITLE
Jellyfin Backend

### ISSUE THREAD

**Issue by valmar** [orontee/argos#48]
Thank you for your amazing work! Would it please be possible to add the Jellyfin backend?

https://github.com/jellyfin/mopidy-jellyfin

Currently, I can control playing using Argos and see the current playing queue, but I cannot see the library from the Jellyfin backend, which is the only active backend for me!

Thank you!!!

**Comment by valmar** [comment]
Of course I will be happy to help testing, etc!

**Comment by orontee** [comment]
Thanks for your feedback!

Since Argos is "album-centric", adding a backend that implements a "library browse by album" endpoint is easy; Otherwise one would have to change the UI, which is time-consuming. I'll have a look to Mopidy-Jellyfin and report back.

**Comment by orontee** [comment]
@valmar Can you post the response to:
```
curl -i -H "Content-Type: application/json" -XPOST http://argos.local/mopidy/rpc -d '{"jsonrpc":"2.0","id": 1,"method":"core.library.browse","params":{"uri": null}}'
```
I expect the response to contain a ref with name "jellyfin"; Note its URI property and please post the response to the following request where you replace JELLYFISH_URI with that URI:

```
curl -i -H "Content-Type: application/json" -XPOST http://argos.local/mopidy/rpc -d '{"jsonrpc":"2.0","id": 1,"method":"core.library.browse","params":{"uri": JELLYFISH_URI}}'
```

**Comment by orontee** [comment]
https://github.com/jellyfin/mopidy-jellyfin/blob/f10b3f47ae83083c901f6b3bd9f2a767f5dd5d3c/mopidy_jellyfin/library.py#L32

Looks like the  "library browse by album" endpoint is implemented.

**Comment by orontee** [comment]
@valmar You can try the [48-jellyfin-backend](https://github.com/orontee/argos/tree/48-jellyfin-backend) branch.

**Comment by valmar** [comment]
Wow yes let me test!!! I will report in a few hours! Thank you so much!!!

**Comment by valmar** [comment]
So, I tested it, and when I start argos, this is what I see in the terminal:

```
2022-08-28 15:12:39,887 EventLoopThread INFO: argos.controllers.albums - Starting to browse albums...
2022-08-28 15:12:40,127 EventLoopThread WARNING: argos.controllers.albums - No known backend supports URI 'jellyfin:'
2022-08-28 15:12:40,127 EventLoopThread WARNING: argos.controllers.albums - Skipping unsupported directory with URI 'jellyfin:'
2022-08-28 15:12:40,128 MainThread INFO: argos.model - Albums loaded
2022-08-28 15:12:40,156 EventLoopThread WARNING: argos.download - Unsupported URI scheme 'http://192.168.50.100:8096/Items
```

And unfortunately the library is not populated!

Let me know if I can help with more testing any time

**Comment by orontee** [comment]
@valmar Thanks, I was wrong when I guessed the "directory" URI of Mopidy-Jellyfin... Just pushed commit 5c60aac which use `directory:` and not `directory:browse`.

In case this new version doesn't work as expected, please post the response to the two `curl` commands above.

**Comment by valmar** [comment]
Thanks @orontee. So the output this time is different. It tells me that the albums are being indexed, but after 10 seconds the library tab goes blank, and in the terminal I see:
```

2022-08-28 23:08:15,137 EventLoopThread INFO: argos.controllers.albums - Starting to browse albums...
2022-08-28 23:08:15,143 EventLoopThread INFO: argos.controllers.albums - Backend MopidyJellyfinBackend supports URI 'jellyfin:albums'
2022-08-28 23:08:15,320 EventLoopThread INFO: argos.controllers.albums - Found 2388 albums in directory with URI 'jellyfin:'
2022-08-28 23:08:25,326 EventLoopThread WARNING: argos.ws - Timeout 10s excedeed while waiting response of JSON-RPC command 14 with method core.library.get_images
2022-08-28 23:08:25,328 MainThread INFO: argos.model - Albums loaded
2022-08-28 23:08:29,073 EventLoopThread WARNING: argos.download - Unsupported URI scheme 'http://192.168.50.100:8096/Items
```

**Comment by valmar** [comment]
I am trying the first curl command above, but it cannot resolve the host `argos.local`. Is this supposed to be the host where argos is running? Or the one where mopidy is running? I apologize for my dumbness!!

**Comment by orontee** [comment]
Yes, but I don't need those information anymore since your previous message shows that album loading is now functional. 
What breaks now is the request to fetch album cover images URIs... 2388 albums... I tested Argos with my 500 albums library, and if I remember well we try to fetch all images URIs in one request for all albums.

I'll have a look.

Thanks for testing!

**Comment by valmar** [comment]
No thank you! Yes, I have a lot of music.... !!! He he

**Comment by orontee** [comment]
I pushed a new commit to fetch album image URIs by slice. This should solve the `Timeout 10s excedeed` warning which resulted on the Jellyfin backend albums being skipped.

Next step, is to load the track list for each album. Be patient! (Note that I found no other way to resolve album artist than fetching the album's tracks...).

**Comment by valmar** [comment]
Thanks @orontee! Even more progress. All the albums appear and I can navigate the tracks! The covers are missing, however, and I see the following in the terminal:
```

2022-08-28 23:51:44,806 EventLoopThread WARNING: argos.download - Unsupported URI scheme 'http://192.168.50.100:8096/Items/181b816f38858275983b7f51109098e1/Images/Primary'
2022-08-28 23:51:44,806 EventLoopThread WARNING: argos.download - Unsupported URI scheme 'http://192.168.50.100:8096/Items/ead392ef5edfbe417685a98349e85f8d/Images/Primary'
2022-08-28 23:51:44,806 EventLoopThread WARNING: argos.download - Unsupported URI scheme 'http://192.168.50.100:8096/Items/7948c4fd08860d53d7acd5e63a3fd8f2/Images/Primary'
2022-08-28 23:51:44,806 EventLoopThread WARNING: argos.download - Unsupported URI scheme 'http://192.168.50.100:8096/Items/6d7bb9f0926cf250035654aaf84f68d4/Images/Primary'
2022-08-28 23:51:44,806 EventLoopThread WARNING: argos.download - Unsupported URI scheme 'http://192.168.50.100:8096/Items/0a95438fd5b98d006c13a274ce98bffe/Images/Primary'
2022-08-28 23:51:44,806 EventLoopThread WARNING: argos.download - Unsupported URI scheme 'http://192.168.50.100:8096/Items/7514ff41db8b72f7a8b1af958b0f80ee/Images/Primary'
```

Repeatedly for many many lines. I think it is failing to fetch the images!

I will go to sleep now, but will be happy to keep testing anything you send me tomorrow! Thanks for all your hard work!

**Comment by orontee** [comment]
> Even more progress. All the albums appear and I can navigate the tracks! 

Great!

> (...) I think it is failing to fetch the images!

Yep. Looks like I forgot to implement download of images with `http` URI scheme. I just pushed a possible fix. Once again not tested on my side, sorry.

(A cache for images is already implemented, thus Argos won't spend time downloading images each time it browse the library.)

**Comment by valmar** [comment]
Works perfectly! I have all the albums with the cover art and I can play and control the playing. This is awesome, thank you so much!

![image](https://user-images.githubusercontent.com/558469/187244779-1b44fcb4-ff82-4c1b-8e88-17e3d7750cff.png)

**Comment by orontee** [comment]
Good news.

Do you use Jellyfin playlists feature? If its the case, do you know if they're homogeneous to Mopidy-M3U playlists? I am asking to know whether it makes sense to factorize the source code handling playlists, so it could support playlists exposed through Mopidy-M3U and Mopidy-Jellyfin...

**Comment by orontee** [comment]
Code squashed and merged, 1917aae.

**Comment by valmar** [comment]
I personally do not use playlist much, but I would be happy to test whatever you code, of course. Let me investigate how the Jellyfin playlists behave

**Comment by orontee** [comment]
> I personally do not use playlist much, but I would be happy to test whatever you code, of course. Let me investigate how the Jellyfin playlists behave

I checked on Argos side and the factorization work to do on playlists isn't trivial. But who knows, I could find time to do that, thus if you don't mind posting the output of the following command (after at least one playlist has been created, and under the hypothesis that Mopidy is listening on port 8096 of the host with IP `192.168.50.100`, adapt to your installation if it's not the case):
```
curl -i -H "Content-Type: application/json" -XPOST http://192.168.50.100:8096/mopidy/rpc -d '{"jsonrpc":"2.0","id": 1,"method":"core.library.browse","params":{"uri": "jellyfin:playlists"}}'
```
Thanks @valmar !

**Comment by valmar** [comment]
@orontee so, the output of the command, after creating a playlist

```
HTTP/1.1 404 Not Found
Content-Length: 0
Date: Thu, 01 Sep 2022 07:00:58 GMT
Server: Kestrel
```

However, the problem might be more subtle. Please see this bug report:

https://github.com/jellyfin/mopidy-jellyfin/issues/110

Specifically, this message:

"Are the playlists just in a library of your music library, or do you actually have a Playlists library on the home page? If it's just a piece of another library then it won't be parsed here, we're specially looking for a library that has the type of Playlists."

My playlist does not appear in a separate library, it's just part of the Music library.

Further down:

"-  Having m3u8 Playlists in Jellyfin in a Music Library does not work
 - Creating a new Testplaylist somewhere in Jellyfin, putting a single Song into it, will make that the API will report all m3u8 Playlists and the new Testplaylist."

However, I only have a Music Library in Jellyfin, so I don't know how to test this!

Thank you again for all your work!

**Comment by valmar** [comment]
Ok one more data point: actually after creating the playlist in the Music library, a new Playlist library appears in Jellyfin. However, that library is empty. I cannot see any playlists in it!

**Comment by orontee** [comment]
Ok, thanks for trying @valmar. No need to waste more time on this: Looks rather complicated!

**Comment by orontee** [comment]
@valmar Last Argos version has an updated library browser, not limited to albums. I expect Jellyfin playlists to now be accessible from there. (I plan to add a playlist detailed view like the one we have for Mopidy-M3U extension; Right now clicking on a playlist from the library browser is expected to enqueue the playlist tracks...).

By the way, loading a huge library like yours shouldn't block user interaction with Mopidy server anymore.

**Comment by valmar** [comment]
Testing it right now! It seems to work perfectly! I can browse Jellyfin by artist and then select the album! This is awesome, thank you!
