### ISSUE TITLE
Don't automatically select first album track

### ISSUE THREAD

**Issue by canddoki** [orontee/argos#53]
@orontee The kids use Argos almost every day, thanks again for that :).

After you set the single-click option as default, I noticed two things:

**Albumview**
When I select an album in the library, after opening the album, the first track is selected. Then I press play and of course only this track is played. This means that every time you want to play an entire album, you have to deselect the first track with one click and then press play. Is it possible after opening an album that no track is selected?

**Preference dialog**
Sort by name, artist, date... When I open the selection box, it immediately closes again. I managed to change the setting but had to be insanely fast ;-). I don't know if there is a single-click solution here. Maybe option buttons...

Many thanks and greetings
André

**Comment by orontee** [comment]
> @orontee The kids use Argos almost every day, thanks again for that :).

Great ! 💕

> After you set the single-click option as default, I noticed two things:
> 
> **Albumview** When I select an album in the library, after opening the album, the first track is selected. Then I press play and of course only this track is played. This means that every time you want to play an entire album, you have to deselect the first track with one click and then press play. Is it possible after opening an album that no track is selected?

Oh yes! I am becoming crazy because of this! Added to the todo list.

> **Preference dialog** Sort by name, artist, date... When I open the selection box, it immediately closes again. I managed to change the setting but had to be insanely fast ;-). I don't know if there is a single-click solution here. Maybe option buttons...

You're right, this combo box isn't working very well on my Raspberry pi with touch screen. My understanding is that one has to touch the right arrow for the choice window to appear and stay open; But the arrow is so small that it's almost impossible to put one's finger on it. 

On my laptop (it has a touch screen) running Debian Bullseye with Gnome, it works well.

The combo box could be replaced by radio buttons. I am just worrying whether the preference dialog would become to tall after this change. May be it's time to introduce tabs in this dialog... What do you think?

**Comment by orontee** [comment]
A fix for the first track selection is available. To be tested. 

#54 has been created to track the other problem.

**Comment by orontee** [comment]
Seems to be working as expected!

**Comment by canddoki** [comment]
@orontee As always the fastest programmer I know :). It works perfectly. Thank you very much and also for the honor of appearing in the about dialog.
I think tabs in the preference dialog is a good idea. There will definitely be some more big things to come in the future :).
What are meaningful names for the tabs? Maybe ...
**Mopidy**
_Mopidy Server_
BaseURL
_Backends_
Local, Podcasts, Bandcamp, Jellyfin, ...
**Appearance**
_General_
Start in Maximized or Kiosk mode
Hide Search Button
Hide Tooltips

_Library_
Sort by album / artist / date
Show Album Name / Artist / both
_Playlists_
Recent Additions
History

Don't worry Argos is doing great, so it's not a todo list, just ideas :).
