### ISSUE TITLE
Add-buttons in playlists and albumview

### ISSUE THREAD

**Issue by canddoki** [orontee/argos#75]
@orontee First of all, I really like the improved Playlists box. It looks much tidier and more consistent to albumview.
Since you are currently working on the gui ;), what do you think about moving the add-buttons in playlists and albumview a bit? With small touchscreens I sometimes hit the wrong button. In my opinion, in albumsview the left side of the column and in playlists right of the edit button are good places. With some space in between, like search and settings buttons. What do you think?

**Comment by orontee** [comment]
> First of all, I really like the improved Playlists box. It looks much tidier and more consistent to albumview.

Yes, I like it too!

> Since you are currently working on the gui ;), what do you think about moving the add-buttons in playlists and albumview a bit? 

I understand your problem. 

May I suggest first you try to create a file `~/.config/gtk-3.0/gtk.css` (or append to that file in case it already exists) with the following content:
```
#playlist-button-box buttonbox button, #album-details-button-box button {
    min-width: 60px;
}
```

On my box it results in the following where buttons are easier to press (you can play with `min-height` too).

![image](https://user-images.githubusercontent.com/2065954/196289420-0161273a-6727-4ca6-a8ee-8163ed738bda.png)

![image](https://user-images.githubusercontent.com/2065954/196289445-b508f887-5bb6-4faf-9eee-d4cee1683f19.png)

**Comment by orontee** [comment]
On my raspberry pi I use the following to enlarge title buttons and the buttons you're interested in:
```
* {
    font-size: 13pt;
}

#tracklist-button-box image, #album-details-button-box image, #playlist-button-box image {
  min-height: 30px;
  min-width: 30x;
}

.titlebar button {
  min-height: 30px;
  min-width: 30px;
}
```

**Comment by orontee** [comment]
My point is that playing with CSS is more flexible than moving buttons. What do you think?

**Comment by canddoki** [comment]
@orontee I've tried Gnome, but never really used it. ... but css file is written and it looks very nice :). Thank you very much for the tip.

**Comment by canddoki** [comment]
@orontee Only another question :) - via CSS styles is it also possible to control the size of the coverpreviews in albumsview?

**Comment by orontee** [comment]
Sure, let me try on my side and I'll post the needed CSS snippet.

**Comment by orontee** [comment]
Hum... I was wrong. Each item isn't an item by itself so it isn't as easy as I expected. Please open an issue and I'll double-check. If not possible through CSS we could provide a preference setting with say three pre-defined sizes...
