### ISSUE TITLE
Size of Coverpreviews in albumsview

### ISSUE THREAD

**Issue by canddoki** [orontee/argos#77]
@orontee  On my 7-inch RPI-Touchscreen I have on the right some space left. Is it possible to change the cover size? Like your proposal via a setting with 3 sizes or maybe with a slider ...?
Thank you and greetings to France :).

**Comment by orontee** [comment]
If your concern is the space left on the right side of the album view then it's not only the size of the images that must be changed but the width of their captions (with album name and artist name) too. Am I right?

I don't think we need a setting for this: The optimal "item" (the square made of a cover image plus its caption) size can be computed from the width of the window at startup in order to limit the size of the space left.

Still being able to choose a preferred image size make sense.

**Comment by orontee** [comment]
In fact, `Gtk.IconView` isn't very flexible and I finally reverted to your initial idea: In branch `77-size-of-coverpreviews-in-albums-view` the size of images in the albums view is customizable through `GSettings` or the preferences dialog.

**Comment by canddoki** [comment]
Yes you are right. I mean the size of the images including the captions.
I have a 7-inch RPI-Display with a resolution of 800px x 480px. After subtract the window borders, there is still a width of 784px. With 4 images next to each other, the optimal width of an item would be 196px. One item here is currently 165px wide.
Now you would have to have a calculation for different window sizes. Maybe:
a = preferred item width, e.g. 150px
x = window width - border
x / a = number of items horizontal
in my example 784px / 150px = 5.2 --> rounded down to 5
optimal item width is 784 / 5 = 156.8 > rounded 156px
The variable a could perhaps be displayed in the settings or to the left of the Now Playing button with maybe three settings, e.g. small (100px), medium (150px) and large (200px).
But ... I don't know if it works like that and how complex it is 😅.

**Comment by canddoki** [comment]
![image](https://user-images.githubusercontent.com/107265121/197031519-6e4bd58c-725c-472e-a09c-f884b47e0bd6.jpeg)

**Comment by orontee** [comment]
> Sorry, I didn't saw your last comment. Thank you, I'll try your solution.

Note that it's still very "fresh" so there may be some bugs... dunno.

**Comment by canddoki** [comment]
No problem, I need a bit time for this test. We are on holidays until the end of next week 😎.

**Comment by orontee** [comment]
Yes, don't worry, no urge. I'll be on holidays next week. And I plan to stay away from the computer. Nice holidays!

**Comment by orontee** [comment]
- [ ] Update preferences screenshot
