### ISSUE TITLE
Preference dialog switch to start maximized

### ISSUE THREAD

**Issue by orontee** [orontee/argos#90]
Will deprecate the corresponding command line option.

**Comment by canddoki** [comment]
@orontee After 'size of cover preview', the 'new title bar buttons' and the 'dark theme' another great improvement. Except for the theme I was able to test everything and it works perfectly.
I have a question about the maximized mode. If the title bar is pressed longer, the full screen mode is exited. The maximize, minimize and close buttons appear. Is it possible to disable this behavior in Gtk?

Thanks and greetings
André

**Comment by orontee** [comment]
Thanks again for your feedbacks, @canddoki !

I know the problem you describe with maximized window on the Raspberry Pi. It's really annoying! 

I've spent some time trying to configure Openbox, the window manager used by LXDE (are you using the same window manager?), to disable the "move and resize using the title bar" features for Argos main window. It was silly since its a "client" title bar (meaning its managed by the application itself, not the window manager). 

I believe there should be a solution through implementation (I must write a function that consume drag events when in the window is maximized). Another solution could be to use fullscreen state and not maximized state (you seems to confuse both states), but still draw a titlebar in fullscreen mode, which is unusual. In conclusion, some ideas but nothing that clear... Unfortunately!

**Comment by canddoki** [comment]
@orontee Yes, I probably have the same configuration, but I didn't realize it was that complicated. Don't worry, it's good for a real kiosk mode, but not a big problem.
I have now removed the cli option "--maximized". Argos starts perfectly with the window maximized. However, the search button is now always visible even though I left the "--hide-search-button" option unchanged. Did you change something here too? Of course, it would be logical to place this function in the preference dialog as well :).

**Comment by orontee** [comment]
> @orontee Yes, I probably have the same configuration, but I didn't realize it was that complicated. Don't worry, it's good for a real kiosk mode, but not a big problem.

Not a big problem, but I find it really annoying.

> I have now removed the cli option "--maximized". Argos starts perfectly with the window maximized. However, the search button is now always visible even though I left the "--hide-search-button" option unchanged. Did you change something here too? 

It's a regression. I'll have a look.

> Of course, it would be logical to place this function in the preference dialog as well :).

I don't think it's a good idea because it's really specific. If there was a way to hide the button through CSS, I'd even consider to remove the command line option!
