### ISSUE TITLE
Command line option --hide-search-button not working as expected

### ISSUE THREAD

**Issue by orontee** [orontee/argos#91]
Created after #90 

@canddoki I failed to reproduce. Aren't you confusing the new "sort" button with the "search" button?

Oh, but I see that there's a bug when using the option causing an unhandled exception. I'll fix this.

**Comment by orontee** [comment]
@canddoki Please confirm is it fixed now. But no urge.

**Comment by canddoki** [comment]
@orontee No, I like the new sort button :) and I understand, it's really special and only makes sense if you don't have a keyboard. I'll give you feedback after testing.
Happy weekend :).
